#!/bin/bash

source ../scripts/func.bash

symlink /system/lib/libbluetooth_jni.so /system/app/Bluetooth/lib/x86/libbluetooth_jni.so
symlink /system/lib/libdefcontainer_jni.so /system/priv-app/DefaultContainerService/lib/x86/libdefcontainer_jni.so
symlink /system/lib/libjni_pacprocessor.so /system/app/PacProcessor/lib/x86/libjni_pacprocessor.so
symlink /system/lib/libprintspooler_jni.so /system/app/PrintSpooler/lib/x86/libprintspooler_jni.so
symlink /system/lib/libthermalJNI.so /system/priv-app/ituxd/lib/x86/libthermalJNI.so
symlink /system/lib/libttscompat.so /system/app/PicoTts/lib/x86/libttscompat.so
symlink /system/lib/libttspico.so /system/app/PicoTts/lib/x86/libttspico.so
symlink Roboto-Bold.ttf /system/fonts/DroidSans-Bold.ttf
symlink Roboto-Regular.ttf /system/fonts/DroidSans.ttf
symlink app_process32 /system/bin/app_process
symlink dalvikvm32 /system/bin/dalvikvm
symlink gralloc.redhookbay.so.1.12.3197934 /system/vendor/lib/hw/gralloc.redhookbay.so
symlink toolbox /system/vendor/lib/hw/gralloc.redhookbay.so.1
symlink libEGL_POWERVR_SGX544_115.so.1.12.3197934 /system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so
symlink toolbox /system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so.1
symlink libGLESv1_CM_POWERVR_SGX544_115.so.1.12.3197934 /system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so
symlink toolbox /system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so.1
symlink libGLESv2.so /system/lib/libGLESv3.so
symlink libGLESv2_POWERVR_SGX544_115.so.1.12.3197934 /system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so
symlink toolbox /system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so.1
symlink libIMGegl.so.1.12.3197934 /system/vendor/lib/libIMGegl.so
symlink toolbox /system/vendor/lib/libIMGegl.so.1
symlink libPVROCL.so.1.12.3197934 /system/vendor/lib/libPVROCL.so
symlink toolbox /system/vendor/lib/libPVROCL.so.1
symlink libPVRScopeServices.so.1.12.3197934 /system/vendor/lib/libPVRScopeServices.so
symlink toolbox /system/vendor/lib/libPVRScopeServices.so.1
symlink libglslcompiler.so.1.12.3197934 /system/vendor/lib/libglslcompiler.so
symlink toolbox /system/vendor/lib/libglslcompiler.so.1
symlink liboclcompiler.so.1.12.3197934 /system/vendor/lib/liboclcompiler.so
symlink toolbox /system/vendor/lib/liboclcompiler.so.1
symlink libpvr2d.so.1.12.3197934 /system/vendor/lib/libpvr2d.so
symlink toolbox /system/vendor/lib/libpvr2d.so.1
symlink libpvrANDROID_WSEGL.so.1.12.3197934 /system/vendor/lib/libpvrANDROID_WSEGL.so
symlink toolbox /system/vendor/lib/libpvrANDROID_WSEGL.so.1
symlink libsrv_init.so.1.12.3197934 /system/vendor/lib/libsrv_init.so
symlink toolbox /system/vendor/lib/libsrv_init.so.1
symlink libsrv_um.so.1.12.3197934 /system/vendor/lib/libsrv_um.so
symlink toolbox /system/vendor/lib/libsrv_um.so.1
symlink libusc.so.1.12.3197934 /system/vendor/lib/libusc.so
symlink toolbox /system/vendor/lib/libusc.so.1
symlink memtrack.redhookbay.so.1.12.3197934 /system/vendor/lib/hw/memtrack.redhookbay.so
symlink toolbox /system/vendor/lib/hw/memtrack.redhookbay.so.1
symlink toolbox /system/bin/cat /system/bin/chcon
symlink toolbox /system/bin/chmod /system/bin/chown /system/bin/clear
symlink toolbox /system/bin/cmp /system/bin/cp /system/bin/date
symlink toolbox /system/bin/dd /system/bin/df /system/bin/dmesg
symlink toolbox /system/bin/du /system/bin/getenforce /system/bin/getevent
symlink toolbox /system/bin/getprop /system/bin/getsebool /system/bin/grep
symlink toolbox /system/bin/hd /system/bin/id /system/bin/ifconfig
symlink toolbox /system/bin/iftop /system/bin/insmod /system/bin/ioctl
symlink toolbox /system/bin/ionice /system/bin/kill /system/bin/ln
symlink toolbox /system/bin/load_policy /system/bin/log /system/bin/ls
symlink toolbox /system/bin/lsmod /system/bin/lsof /system/bin/md5
symlink toolbox /system/bin/mkdir /system/bin/mknod /system/bin/mkswap
symlink toolbox /system/bin/mount /system/bin/mv /system/bin/nandread
symlink toolbox /system/bin/netstat /system/bin/newfs_msdos /system/bin/nohup
symlink toolbox /system/bin/notify /system/bin/printenv /system/bin/ps
symlink toolbox /system/bin/readlink /system/bin/renice /system/bin/restorecon
symlink toolbox /system/bin/rm /system/bin/rmdir /system/bin/rmmod
symlink toolbox /system/bin/route /system/bin/runcon /system/bin/schedtop
symlink toolbox /system/bin/sendevent /system/bin/setenforce
symlink toolbox /system/bin/setprop /system/bin/setsebool /system/bin/sleep
symlink toolbox /system/bin/smd /system/bin/start /system/bin/stop
symlink toolbox /system/bin/swapoff /system/bin/swapon /system/bin/sync
symlink toolbox /system/bin/top /system/bin/touch /system/bin/umount
symlink toolbox /system/bin/uptime /system/bin/vmstat /system/bin/watchprops
symlink toolbox /system/bin/wipe
set_metadata_recursive /system 0 0 0755 0644
set_metadata_recursive /system/bin 0 2000 0755 0755
set_metadata /system/bin/a600cg_akmd09911 0 2000 0755
set_metadata /system/bin/akmd09911 0 2000 0755
set_metadata /system/bin/app_process32 0 2000 0755
set_metadata /system/bin/asuslogcat 0 2000 0755
set_metadata /system/bin/bcu_cpufreqrel 0 2000 0755
set_metadata /system/bin/bootanimation 0 2000 0755
set_metadata /system/bin/clatd 0 2000 0755
set_metadata /system/bin/crashlogd 0 2000 0755
set_metadata /system/bin/debuggerd 0 2000 0755
set_metadata /system/bin/dex2oat 0 2000 0755
set_metadata /system/bin/dhcpcd 0 2000 0755
set_metadata /system/bin/dnsmasq 0 2000 0755
set_metadata /system/bin/dpstmgr 0 2000 0755
set_metadata /system/bin/drmserver 0 2000 0755
set_metadata /system/bin/dumpstate 0 2000 0755
set_metadata /system/bin/fdcmts 0 2000 0755
set_metadata /system/bin/fg_conf 0 2000 0755
set_metadata /system/bin/gpsd 0 2000 0755
set_metadata /system/bin/gpslogd 0 2000 0755
set_metadata /system/bin/hostapd 0 2000 0755
set_metadata /system/bin/install-recovery.sh 0 0 0750
set_metadata /system/bin/installd 0 2000 0755
set_metadata /system/bin/keystore 0 2000 0755
set_metadata /system/bin/lmkd 0 2000 0755
set_metadata /system/bin/logcat 0 2000 0755
set_metadata /system/bin/logcommand 0 2000 0755
set_metadata /system/bin/logcontrol 0 2000 0755
set_metadata /system/bin/logd 0 2000 0755
set_metadata /system/bin/logkmsg 0 2000 0755
set_metadata /system/bin/mdnsd 0 2000 0755
set_metadata /system/bin/mediaserver 0 2000 0755
set_metadata /system/bin/mmgr 0 2000 0755
set_metadata /system/bin/mtpd 0 2000 0755
set_metadata /system/bin/netcfg 0 3003 02750
set_metadata /system/bin/netd 0 2000 0755
set_metadata /system/bin/nvm_server 0 2000 0755
set_metadata /system/bin/patchoat 0 2000 0755
set_metadata /system/bin/ping 0 0 0755
set_metadata /system/bin/pppd 0 2000 0755
set_metadata /system/bin/racoon 0 2000 0755
set_metadata /system/bin/rild 0 2000 0755
set_metadata /system/bin/run-as 0 2000 0750
set_metadata /system/bin/sdcard 0 2000 0755
set_metadata /system/bin/servicemanager 0 2000 0755
set_metadata /system/bin/sh 0 2000 0755
set_metadata /system/bin/surfaceflinger 0 2000 0755
set_metadata /system/bin/toolcommand 0 2000 0755
set_metadata /system/bin/toolconnect 0 2000 0755
set_metadata /system/bin/uncrypt 0 0 0750
set_metadata /system/bin/upi_ug31xx 0 2000 0755
set_metadata /system/bin/vdc 0 2000 0755
set_metadata /system/bin/vold 0 2000 0755
set_metadata /system/bin/wpa_supplicant 0 2000 0755
set_metadata /system/etc/dhcpcd/dhcpcd-run-hooks 1014 2000 0550
set_metadata_recursive /system/etc/ppp 0 0 0755 0555
set_metadata /system/recovery-from-boot.p 0 0 0644
set_metadata /system/vendor 0 2000 0755
set_metadata_recursive /system/vendor/bin 0 2000 0755 0755
set_metadata /system/vendor/bin 0 2000 0755
set_metadata /system/vendor/etc 0 2000 0755
set_metadata /system/vendor/firmware 0 2000 0755
set_metadata /system/vendor/firmware/telephony 0 2000 0755
set_metadata /system/vendor/lib 0 2000 0755
set_metadata_recursive /system/vendor/lib/drm 0 2000 0755 0644
set_metadata /system/vendor/lib/drm/libdrmwvmplugin.so 0 0 0644
set_metadata /system/vendor/lib/egl 0 2000 0755
set_metadata /system/vendor/lib/hw 0 2000 0755
set_metadata /system/vendor/lib/mediadrm 0 2000 0755
set_metadata /system/vendor/media 0 2000 0755
set_metadata_recursive /system/xbin 0 2000 0755 0755
