#!/bin/bash

source ../scripts/func.bash

cp system/bin/sh system/xbin/sugote-mksh
mkdir system/bin/.ext
cp system/xbin/su system/bin/.ext/.su
cp system/xbin/su system/xbin/sugote
cp system/xbin/su system/xbin/daemonsu

rm system/bin/app_process
ln -s /system/xbin/daemonsu system/bin/app_process
mv system/bin/app_process32 system/bin/app_process32_original
ln -s /system/xbin/daemonsu system/bin/app_process32
cp system/bin/app_process32_original system/bin/app_process_init
set_perm 0 2000 755 /system/bin/app_process_init

set_perm 0 0 0777 /system/bin/.ext
set_perm 0 0 0755 /system/bin/.ext/.su
set_perm 0 0 0755 /system/xbin/su
set_perm 0 0 0755 /system/xbin/sugote
set_perm 0 0 0755 /system/xbin/sugote-mksh
set_perm 0 0 0755 /system/xbin/supolicy
set_perm 0 0 0644 /system/lib/libsupol.so
set_perm 0 0 0755 /system/xbin/daemonsu
set_perm 0 0 0755 /system/app/SuperSU
set_perm 0 0 0644 /system/app/SuperSU/SuperSU.apk
set_perm 0 0 0644 /system/etc/.installed_su_daemon
